require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/team_levels", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # TeamLevel. As you add validations to TeamLevel, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      TeamLevel.create! valid_attributes
      get team_levels_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      team_level = TeamLevel.create! valid_attributes
      get team_level_url(team_level)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_team_level_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      team_level = TeamLevel.create! valid_attributes
      get edit_team_level_url(team_level)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new TeamLevel" do
        expect {
          post team_levels_url, params: { team_level: valid_attributes }
        }.to change(TeamLevel, :count).by(1)
      end

      it "redirects to the created team_level" do
        post team_levels_url, params: { team_level: valid_attributes }
        expect(response).to redirect_to(team_level_url(TeamLevel.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new TeamLevel" do
        expect {
          post team_levels_url, params: { team_level: invalid_attributes }
        }.to change(TeamLevel, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post team_levels_url, params: { team_level: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested team_level" do
        team_level = TeamLevel.create! valid_attributes
        patch team_level_url(team_level), params: { team_level: new_attributes }
        team_level.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the team_level" do
        team_level = TeamLevel.create! valid_attributes
        patch team_level_url(team_level), params: { team_level: new_attributes }
        team_level.reload
        expect(response).to redirect_to(team_level_url(team_level))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        team_level = TeamLevel.create! valid_attributes
        patch team_level_url(team_level), params: { team_level: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested team_level" do
      team_level = TeamLevel.create! valid_attributes
      expect {
        delete team_level_url(team_level)
      }.to change(TeamLevel, :count).by(-1)
    end

    it "redirects to the team_levels list" do
      team_level = TeamLevel.create! valid_attributes
      delete team_level_url(team_level)
      expect(response).to redirect_to(team_levels_url)
    end
  end
end
